apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: curl-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: curl-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: curl-rolebinding
subjects:
  - kind: ServiceAccount
    name: curl-sa
roleRef:
  kind: Role
  name: curl-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: curl-pod
spec:
  serviceAccountName: curl-sa
  containers:
    - name: curl-container
      image: curlimages/curl
      command: ["sleep", "infinity"]